pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        mavenLocal()
    }
}

rootProject.name = "PawnAI Recorder"
include ':template'

includeBuild('../../pawnai-sqs/kotlin') {
    dependencySubstitution {
        substitute module('dev.pawnai:pawn-queue') using project(':pawn-queue')
    }
}
