// pawn_recorder_droid/settings.gradle
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://chaquo.com/maven' }
    }
    plugins {
        id 'com.android.application' version '8.3.2'
        id 'org.jetbrains.kotlin.android' version '1.9.24'
        id 'com.chaquo.python' version '15.0.1'
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://chaquo.com/maven' }
    }
}

rootProject.name = 'pawn_recorder_droid'
include ':app'
